### ISSUE TITLE
TESS QLP data

### ISSUE THREAD

**Issue by pavolgaj** [hpparvi/opents#6]
Hi,
how to use QLP data from TESS (https://archive.stsci.edu/hlsp/qlp) with opents? Is it possible? When I tried it, I got this error:

`OpenTS - Open exoplanet transit search pipeline`
`===============================================`
` - Running the search for data files in '/home/pavolg/fits-qlp'`
` - Saving results to '/home/pavolg/fits-qlp'`
` - Saving plots to '/home/pavolg/fits-qlp'`
` - Running in serial mode`
`Traceback (most recent call last):`
`  File "/usr/local/bin/opents", line 4, in <module>`
`    __import__('pkg_resources').run_script('OpenTS==1.0.0b0', 'opents')`
`  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 651, in run_script`
`    self.require(requires)[0].run_script(script_name, ns)`
`  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 1448, in run_script`
`    exec(code, namespace, namespace)`
`  File "/usr/local/lib/python3.8/dist-packages/OpenTS-1.0.0b0-py3.8.egg/EGG-INFO/scripts/opents", line 197, in <module>`
`    logger.info(f"Chose {TSC.__name__} transit search class")`
`AttributeError: 'NoneType' object has no attribute '__name__'`

Other sources of data (TESS 2-minute cadence data, data from Eleanor) work fine.

**Comment by pavolgaj** [comment]
I just see a dev branch where the problem is already solved.
